language: ruby
sudo: false

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 4a00ba41fd81fb3089221fcf03e9fc226a356f1f80f29ebe712d181f1b4c2933

install:
  - bundle install

script:
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter
